version: "3"

services:
  clash:
    image: starudream/clash
    volumes:
      - /opt/docker/clash/config.yaml:/root/.config/clash/config.yaml:ro
  clash-speedtest:
    image: starudream/clash-speedtest
    depends_on:
      - clash
    volumes:
      - /opt/docker/clash/result:/result
    environment:
      URL: http://clash:9090
      PROXY: http://clash:7890
      RETRY: 1
      TIMEOUT: 5s
      INCLUDE:
      EXCLUDE:
      OUTPUT: /result
